shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'), 
    path('course/<int:course_id>', views.single_course, name='single_course')
]

shop/models.py
from django.db import models
from django.utils import timezone

# Create you here.


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    created_at = models.DateTimeField(
        default=timezone.now, verbose_name='Дата создания')

    class Meta():
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    price = models.FloatField(verbose_name='Цена')
    students_qty = models.IntegerField(verbose_name='Количество студентов')
    reviews_qty = models.IntegerField(verbose_name='Количество отзывов')
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Категория')
    created_at = models.DateTimeField(
        default=timezone.now, verbose_name='Дата создания')

    class Meta():
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    def __str__(self):
        return self.title

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Course


# Create your views here.


def index(request):
    courses = Course.objects.all()
    return render(request, 'courses.html', {'courses': courses})


def single_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'single_course.html', {'course': course})

def buy_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'buy_course.html', {'course': course})

shop/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Courses</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a href={% url "shop:index" %} class="navbar-brand">Courses</a>
        <span class="navbar-text">
          <a href="/admin/" class="me-2">Admin</a>
          <a href="/api/v1/">API</a>
        </span>
      </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main> 
  </body>
</html>

shop/templates/courses.html
{%  extends "base.html" %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>
<table class='table mt-5 table-bordered table-striped table-hover'>
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students qty</th>
            <th>Reviews qty</th>
            <th>Buy</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td>
              <a href={% url 'shop:single_course' course.id %}>{{ course.title }}</a>
            </td>
            <td>{{ course.category }}</td>
            <td>{{ course.price }}</td>
            <td>{{ course.students_qty }}</td>
            <td>{{ course.reviews_qty }}</td>
            <td><button class="btn btn-primary"><a>Buy</a></button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>  
{% endblock %}

shop/templates/single_course.html
{% extends "base.html" %}

<title>{{ course.title }}</title>

{% block content %}
<h1 class='mt-5'>{{ course.title }}</h1>
<h2>{{ course.category }}</h2>
<p>Price: {{ course.price }}</p>
<p>Students qty: {{ course.students_qty }}</p>
<button class='btn btn-primary'><a>Buy</a></button>
{% endblock content %}